name: Fact Check Video Queue

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  issues: write

jobs:
  process-queue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import yt_dlp; print('yt-dlp imported successfully')"
      
      - name: Test yt-dlp
        run: |
          python -c "
          import yt_dlp
          # Test with a known working video (Rick Astley)
          try:
              ydl_opts = {'quiet': True, 'no_warnings': True}
              with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                  info = ydl.extract_info('https://www.youtube.com/watch?v=dQw4w9WgXcQ', download=False)
                  print(f'✅ yt-dlp works! Video title: {info.get(\"title\", \"Unknown\")}')
          except Exception as e:
              print(f'❌ yt-dlp test failed: {e}')
          "
      
      
      - name: Process fact-check queue
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/process_queue.py
      
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          git commit -m "Add fact check results" || echo "No changes to commit"
          git push
