name: Fact Check Video

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  issues: write

jobs:
  process-video:
    runs-on: ubuntu-latest
    # Only run if issue title starts with "Fact-check:"
    if: startsWith(github.event.issue.title, 'Fact-check:')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import json, re; print('Dependencies installed successfully')"
      
      - name: Process single issue
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python scripts/process_single_issue.py
      
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          git commit -m "Add fact check results for issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push
